# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b40a02a9b4e8b4983c36a9e3d3d50871a333c9ab03cec06eb7d17d02af94debafbaec529df61522a50673e8e14cfaf07acc83031328f4e80ae3e2d97dfffea36

test:
  secret_key_base: 7b42696d4ce170b15f7a18a4ce4b0dc875058a4bf70ea1dbf04d04de2316054e7fd0caf508873015f5a5f1e99de79a8c780c07ad541b61a7ba71f7399f855a63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
